// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: grpc/proto.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Status int32

const (
	Status_FAIL      Status = 0
	Status_SUCCESS   Status = 1
	Status_EXCEPTION Status = 2
)

// Enum value maps for Status.
var (
	Status_name = map[int32]string{
		0: "FAIL",
		1: "SUCCESS",
		2: "EXCEPTION",
	}
	Status_value = map[string]int32{
		"FAIL":      0,
		"SUCCESS":   1,
		"EXCEPTION": 2,
	}
)

func (x Status) Enum() *Status {
	p := new(Status)
	*p = x
	return p
}

func (x Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Status) Descriptor() protoreflect.EnumDescriptor {
	return file_grpc_proto_proto_enumTypes[0].Descriptor()
}

func (Status) Type() protoreflect.EnumType {
	return &file_grpc_proto_proto_enumTypes[0]
}

func (x Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Status.Descriptor instead.
func (Status) EnumDescriptor() ([]byte, []int) {
	return file_grpc_proto_proto_rawDescGZIP(), []int{0}
}

type BidRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	LamportTimestamp int64                  `protobuf:"varint,1,opt,name=lamport_timestamp,json=lamportTimestamp,proto3" json:"lamport_timestamp,omitempty"`
	ClientId         string                 `protobuf:"bytes,2,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	Amount           int64                  `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *BidRequest) Reset() {
	*x = BidRequest{}
	mi := &file_grpc_proto_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BidRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BidRequest) ProtoMessage() {}

func (x *BidRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BidRequest.ProtoReflect.Descriptor instead.
func (*BidRequest) Descriptor() ([]byte, []int) {
	return file_grpc_proto_proto_rawDescGZIP(), []int{0}
}

func (x *BidRequest) GetLamportTimestamp() int64 {
	if x != nil {
		return x.LamportTimestamp
	}
	return 0
}

func (x *BidRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *BidRequest) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type Acknowledgement struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	LamportTimestamp int64                  `protobuf:"varint,1,opt,name=lamport_timestamp,json=lamportTimestamp,proto3" json:"lamport_timestamp,omitempty"`
	ServerId         string                 `protobuf:"bytes,2,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	Status           string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Acknowledgement) Reset() {
	*x = Acknowledgement{}
	mi := &file_grpc_proto_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Acknowledgement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Acknowledgement) ProtoMessage() {}

func (x *Acknowledgement) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Acknowledgement.ProtoReflect.Descriptor instead.
func (*Acknowledgement) Descriptor() ([]byte, []int) {
	return file_grpc_proto_proto_rawDescGZIP(), []int{1}
}

func (x *Acknowledgement) GetLamportTimestamp() int64 {
	if x != nil {
		return x.LamportTimestamp
	}
	return 0
}

func (x *Acknowledgement) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *Acknowledgement) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type SubscribeRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	LamportTimestamp int64                  `protobuf:"varint,1,opt,name=lamport_timestamp,json=lamportTimestamp,proto3" json:"lamport_timestamp,omitempty"`
	ClientId         string                 `protobuf:"bytes,2,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SubscribeRequest) Reset() {
	*x = SubscribeRequest{}
	mi := &file_grpc_proto_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeRequest) ProtoMessage() {}

func (x *SubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeRequest.ProtoReflect.Descriptor instead.
func (*SubscribeRequest) Descriptor() ([]byte, []int) {
	return file_grpc_proto_proto_rawDescGZIP(), []int{2}
}

func (x *SubscribeRequest) GetLamportTimestamp() int64 {
	if x != nil {
		return x.LamportTimestamp
	}
	return 0
}

func (x *SubscribeRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

type Result struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	LamportTimestamp int64                  `protobuf:"varint,1,opt,name=lamport_timestamp,json=lamportTimestamp,proto3" json:"lamport_timestamp,omitempty"`
	ServerId         string                 `protobuf:"bytes,2,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	Amount           int64                  `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	ClientId         string                 `protobuf:"bytes,4,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Result) Reset() {
	*x = Result{}
	mi := &file_grpc_proto_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Result) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Result) ProtoMessage() {}

func (x *Result) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Result.ProtoReflect.Descriptor instead.
func (*Result) Descriptor() ([]byte, []int) {
	return file_grpc_proto_proto_rawDescGZIP(), []int{3}
}

func (x *Result) GetLamportTimestamp() int64 {
	if x != nil {
		return x.LamportTimestamp
	}
	return 0
}

func (x *Result) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *Result) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *Result) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

type QueryRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	LamportTimestamp int64                  `protobuf:"varint,1,opt,name=lamport_timestamp,json=lamportTimestamp,proto3" json:"lamport_timestamp,omitempty"`
	ClientId         string                 `protobuf:"bytes,2,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *QueryRequest) Reset() {
	*x = QueryRequest{}
	mi := &file_grpc_proto_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryRequest) ProtoMessage() {}

func (x *QueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryRequest.ProtoReflect.Descriptor instead.
func (*QueryRequest) Descriptor() ([]byte, []int) {
	return file_grpc_proto_proto_rawDescGZIP(), []int{4}
}

func (x *QueryRequest) GetLamportTimestamp() int64 {
	if x != nil {
		return x.LamportTimestamp
	}
	return 0
}

func (x *QueryRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

type AuctionStatus struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	LamportTimestamp int64                  `protobuf:"varint,1,opt,name=lamport_timestamp,json=lamportTimestamp,proto3" json:"lamport_timestamp,omitempty"`
	ServerId         string                 `protobuf:"bytes,2,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	ClientId         string                 `protobuf:"bytes,3,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	HighestBid       int64                  `protobuf:"varint,4,opt,name=highest_bid,json=highestBid,proto3" json:"highest_bid,omitempty"`
	LeaderId         string                 `protobuf:"bytes,5,opt,name=leader_id,json=leaderId,proto3" json:"leader_id,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *AuctionStatus) Reset() {
	*x = AuctionStatus{}
	mi := &file_grpc_proto_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuctionStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuctionStatus) ProtoMessage() {}

func (x *AuctionStatus) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuctionStatus.ProtoReflect.Descriptor instead.
func (*AuctionStatus) Descriptor() ([]byte, []int) {
	return file_grpc_proto_proto_rawDescGZIP(), []int{5}
}

func (x *AuctionStatus) GetLamportTimestamp() int64 {
	if x != nil {
		return x.LamportTimestamp
	}
	return 0
}

func (x *AuctionStatus) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *AuctionStatus) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *AuctionStatus) GetHighestBid() int64 {
	if x != nil {
		return x.HighestBid
	}
	return 0
}

func (x *AuctionStatus) GetLeaderId() string {
	if x != nil {
		return x.LeaderId
	}
	return ""
}

type Ping struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	LamportTimestamp int64                  `protobuf:"varint,1,opt,name=lamport_timestamp,json=lamportTimestamp,proto3" json:"lamport_timestamp,omitempty"`
	LeaderId         string                 `protobuf:"bytes,2,opt,name=leader_id,json=leaderId,proto3" json:"leader_id,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Ping) Reset() {
	*x = Ping{}
	mi := &file_grpc_proto_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ping) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ping) ProtoMessage() {}

func (x *Ping) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ping.ProtoReflect.Descriptor instead.
func (*Ping) Descriptor() ([]byte, []int) {
	return file_grpc_proto_proto_rawDescGZIP(), []int{6}
}

func (x *Ping) GetLamportTimestamp() int64 {
	if x != nil {
		return x.LamportTimestamp
	}
	return 0
}

func (x *Ping) GetLeaderId() string {
	if x != nil {
		return x.LeaderId
	}
	return ""
}

type PingReply struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	LamportTimestamp int64                  `protobuf:"varint,1,opt,name=lamport_timestamp,json=lamportTimestamp,proto3" json:"lamport_timestamp,omitempty"`
	NodeId           string                 `protobuf:"bytes,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Alive            bool                   `protobuf:"varint,3,opt,name=alive,proto3" json:"alive,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *PingReply) Reset() {
	*x = PingReply{}
	mi := &file_grpc_proto_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingReply) ProtoMessage() {}

func (x *PingReply) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingReply.ProtoReflect.Descriptor instead.
func (*PingReply) Descriptor() ([]byte, []int) {
	return file_grpc_proto_proto_rawDescGZIP(), []int{7}
}

func (x *PingReply) GetLamportTimestamp() int64 {
	if x != nil {
		return x.LamportTimestamp
	}
	return 0
}

func (x *PingReply) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *PingReply) GetAlive() bool {
	if x != nil {
		return x.Alive
	}
	return false
}

type VoteRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	LamportTimestamp int64                  `protobuf:"varint,1,opt,name=lamport_timestamp,json=lamportTimestamp,proto3" json:"lamport_timestamp,omitempty"`
	CandidateId      string                 `protobuf:"bytes,2,opt,name=candidate_id,json=candidateId,proto3" json:"candidate_id,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *VoteRequest) Reset() {
	*x = VoteRequest{}
	mi := &file_grpc_proto_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VoteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VoteRequest) ProtoMessage() {}

func (x *VoteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VoteRequest.ProtoReflect.Descriptor instead.
func (*VoteRequest) Descriptor() ([]byte, []int) {
	return file_grpc_proto_proto_rawDescGZIP(), []int{8}
}

func (x *VoteRequest) GetLamportTimestamp() int64 {
	if x != nil {
		return x.LamportTimestamp
	}
	return 0
}

func (x *VoteRequest) GetCandidateId() string {
	if x != nil {
		return x.CandidateId
	}
	return ""
}

type VoteReply struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	LamportTimestamp int64                  `protobuf:"varint,1,opt,name=lamport_timestamp,json=lamportTimestamp,proto3" json:"lamport_timestamp,omitempty"`
	NodeId           string                 `protobuf:"bytes,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	VoteGranted      bool                   `protobuf:"varint,3,opt,name=vote_granted,json=voteGranted,proto3" json:"vote_granted,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *VoteReply) Reset() {
	*x = VoteReply{}
	mi := &file_grpc_proto_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VoteReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VoteReply) ProtoMessage() {}

func (x *VoteReply) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VoteReply.ProtoReflect.Descriptor instead.
func (*VoteReply) Descriptor() ([]byte, []int) {
	return file_grpc_proto_proto_rawDescGZIP(), []int{9}
}

func (x *VoteReply) GetLamportTimestamp() int64 {
	if x != nil {
		return x.LamportTimestamp
	}
	return 0
}

func (x *VoteReply) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *VoteReply) GetVoteGranted() bool {
	if x != nil {
		return x.VoteGranted
	}
	return false
}

type StateUpdate struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	LamportTimestamp int64                  `protobuf:"varint,1,opt,name=lamport_timestamp,json=lamportTimestamp,proto3" json:"lamport_timestamp,omitempty"`
	LeaderId         string                 `protobuf:"bytes,2,opt,name=leader_id,json=leaderId,proto3" json:"leader_id,omitempty"`
	HighestBid       int64                  `protobuf:"varint,3,opt,name=highest_bid,json=highestBid,proto3" json:"highest_bid,omitempty"`
	HighestBidder    string                 `protobuf:"bytes,4,opt,name=highest_bidder,json=highestBidder,proto3" json:"highest_bidder,omitempty"`
	AuctionOver      bool                   `protobuf:"varint,5,opt,name=auction_over,json=auctionOver,proto3" json:"auction_over,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *StateUpdate) Reset() {
	*x = StateUpdate{}
	mi := &file_grpc_proto_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StateUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StateUpdate) ProtoMessage() {}

func (x *StateUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StateUpdate.ProtoReflect.Descriptor instead.
func (*StateUpdate) Descriptor() ([]byte, []int) {
	return file_grpc_proto_proto_rawDescGZIP(), []int{10}
}

func (x *StateUpdate) GetLamportTimestamp() int64 {
	if x != nil {
		return x.LamportTimestamp
	}
	return 0
}

func (x *StateUpdate) GetLeaderId() string {
	if x != nil {
		return x.LeaderId
	}
	return ""
}

func (x *StateUpdate) GetHighestBid() int64 {
	if x != nil {
		return x.HighestBid
	}
	return 0
}

func (x *StateUpdate) GetHighestBidder() string {
	if x != nil {
		return x.HighestBidder
	}
	return ""
}

func (x *StateUpdate) GetAuctionOver() bool {
	if x != nil {
		return x.AuctionOver
	}
	return false
}

type StateAck struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	LamportTimestamp int64                  `protobuf:"varint,1,opt,name=lamport_timestamp,json=lamportTimestamp,proto3" json:"lamport_timestamp,omitempty"`
	NodeId           string                 `protobuf:"bytes,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Accepted         bool                   `protobuf:"varint,3,opt,name=accepted,proto3" json:"accepted,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *StateAck) Reset() {
	*x = StateAck{}
	mi := &file_grpc_proto_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StateAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StateAck) ProtoMessage() {}

func (x *StateAck) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StateAck.ProtoReflect.Descriptor instead.
func (*StateAck) Descriptor() ([]byte, []int) {
	return file_grpc_proto_proto_rawDescGZIP(), []int{11}
}

func (x *StateAck) GetLamportTimestamp() int64 {
	if x != nil {
		return x.LamportTimestamp
	}
	return 0
}

func (x *StateAck) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *StateAck) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

var File_grpc_proto_proto protoreflect.FileDescriptor

const file_grpc_proto_proto_rawDesc = "" +
	"\n" +
	"\x10grpc/proto.proto\"n\n" +
	"\n" +
	"BidRequest\x12+\n" +
	"\x11lamport_timestamp\x18\x01 \x01(\x03R\x10lamportTimestamp\x12\x1b\n" +
	"\tclient_id\x18\x02 \x01(\tR\bclientId\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x03R\x06amount\"s\n" +
	"\x0fAcknowledgement\x12+\n" +
	"\x11lamport_timestamp\x18\x01 \x01(\x03R\x10lamportTimestamp\x12\x1b\n" +
	"\tserver_id\x18\x02 \x01(\tR\bserverId\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\"\\\n" +
	"\x10SubscribeRequest\x12+\n" +
	"\x11lamport_timestamp\x18\x01 \x01(\x03R\x10lamportTimestamp\x12\x1b\n" +
	"\tclient_id\x18\x02 \x01(\tR\bclientId\"\x87\x01\n" +
	"\x06Result\x12+\n" +
	"\x11lamport_timestamp\x18\x01 \x01(\x03R\x10lamportTimestamp\x12\x1b\n" +
	"\tserver_id\x18\x02 \x01(\tR\bserverId\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x03R\x06amount\x12\x1b\n" +
	"\tclient_id\x18\x04 \x01(\tR\bclientId\"X\n" +
	"\fQueryRequest\x12+\n" +
	"\x11lamport_timestamp\x18\x01 \x01(\x03R\x10lamportTimestamp\x12\x1b\n" +
	"\tclient_id\x18\x02 \x01(\tR\bclientId\"\xb4\x01\n" +
	"\rAuctionStatus\x12+\n" +
	"\x11lamport_timestamp\x18\x01 \x01(\x03R\x10lamportTimestamp\x12\x1b\n" +
	"\tserver_id\x18\x02 \x01(\tR\bserverId\x12\x1b\n" +
	"\tclient_id\x18\x03 \x01(\tR\bclientId\x12\x1f\n" +
	"\vhighest_bid\x18\x04 \x01(\x03R\n" +
	"highestBid\x12\x1b\n" +
	"\tleader_id\x18\x05 \x01(\tR\bleaderId\"P\n" +
	"\x04Ping\x12+\n" +
	"\x11lamport_timestamp\x18\x01 \x01(\x03R\x10lamportTimestamp\x12\x1b\n" +
	"\tleader_id\x18\x02 \x01(\tR\bleaderId\"g\n" +
	"\tPingReply\x12+\n" +
	"\x11lamport_timestamp\x18\x01 \x01(\x03R\x10lamportTimestamp\x12\x17\n" +
	"\anode_id\x18\x02 \x01(\tR\x06nodeId\x12\x14\n" +
	"\x05alive\x18\x03 \x01(\bR\x05alive\"]\n" +
	"\vVoteRequest\x12+\n" +
	"\x11lamport_timestamp\x18\x01 \x01(\x03R\x10lamportTimestamp\x12!\n" +
	"\fcandidate_id\x18\x02 \x01(\tR\vcandidateId\"t\n" +
	"\tVoteReply\x12+\n" +
	"\x11lamport_timestamp\x18\x01 \x01(\x03R\x10lamportTimestamp\x12\x17\n" +
	"\anode_id\x18\x02 \x01(\tR\x06nodeId\x12!\n" +
	"\fvote_granted\x18\x03 \x01(\bR\vvoteGranted\"\xc2\x01\n" +
	"\vStateUpdate\x12+\n" +
	"\x11lamport_timestamp\x18\x01 \x01(\x03R\x10lamportTimestamp\x12\x1b\n" +
	"\tleader_id\x18\x02 \x01(\tR\bleaderId\x12\x1f\n" +
	"\vhighest_bid\x18\x03 \x01(\x03R\n" +
	"highestBid\x12%\n" +
	"\x0ehighest_bidder\x18\x04 \x01(\tR\rhighestBidder\x12!\n" +
	"\fauction_over\x18\x05 \x01(\bR\vauctionOver\"l\n" +
	"\bStateAck\x12+\n" +
	"\x11lamport_timestamp\x18\x01 \x01(\x03R\x10lamportTimestamp\x12\x17\n" +
	"\anode_id\x18\x02 \x01(\tR\x06nodeId\x12\x1a\n" +
	"\baccepted\x18\x03 \x01(\bR\baccepted*.\n" +
	"\x06Status\x12\b\n" +
	"\x04FAIL\x10\x00\x12\v\n" +
	"\aSUCCESS\x10\x01\x12\r\n" +
	"\tEXCEPTION\x10\x0225\n" +
	"\aBidding\x12*\n" +
	"\x03Bid\x12\v.BidRequest\x1a\x10.Acknowledgement\"\x00(\x010\x0126\n" +
	"\aAuction\x12+\n" +
	"\tSubscribe\x12\x11.SubscribeRequest\x1a\a.Result\"\x000\x012<\n" +
	"\x05Query\x123\n" +
	"\x10GetAuctionStatus\x12\r.QueryRequest\x1a\x0e.AuctionStatus\"\x002\xb4\x01\n" +
	"\n" +
	"NodeToNode\x12\x1f\n" +
	"\bSendPing\x12\x05.Ping\x1a\n" +
	".PingReply\"\x00\x12(\n" +
	"\n" +
	"AskForVote\x12\f.VoteRequest\x1a\n" +
	".VoteReply\"\x00\x12,\n" +
	"\x0fSendStateUpdate\x12\f.StateUpdate\x1a\t.StateAck\"\x00\x12-\n" +
	"\n" +
	"ForwardBid\x12\v.BidRequest\x1a\x10.Acknowledgement\"\x00B\x0eZ\fauction/grpcb\x06proto3"

var (
	file_grpc_proto_proto_rawDescOnce sync.Once
	file_grpc_proto_proto_rawDescData []byte
)

func file_grpc_proto_proto_rawDescGZIP() []byte {
	file_grpc_proto_proto_rawDescOnce.Do(func() {
		file_grpc_proto_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_grpc_proto_proto_rawDesc), len(file_grpc_proto_proto_rawDesc)))
	})
	return file_grpc_proto_proto_rawDescData
}

var file_grpc_proto_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_grpc_proto_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_grpc_proto_proto_goTypes = []any{
	(Status)(0),              // 0: Status
	(*BidRequest)(nil),       // 1: BidRequest
	(*Acknowledgement)(nil),  // 2: Acknowledgement
	(*SubscribeRequest)(nil), // 3: SubscribeRequest
	(*Result)(nil),           // 4: Result
	(*QueryRequest)(nil),     // 5: QueryRequest
	(*AuctionStatus)(nil),    // 6: AuctionStatus
	(*Ping)(nil),             // 7: Ping
	(*PingReply)(nil),        // 8: PingReply
	(*VoteRequest)(nil),      // 9: VoteRequest
	(*VoteReply)(nil),        // 10: VoteReply
	(*StateUpdate)(nil),      // 11: StateUpdate
	(*StateAck)(nil),         // 12: StateAck
}
var file_grpc_proto_proto_depIdxs = []int32{
	1,  // 0: Bidding.Bid:input_type -> BidRequest
	3,  // 1: Auction.Subscribe:input_type -> SubscribeRequest
	5,  // 2: Query.GetAuctionStatus:input_type -> QueryRequest
	7,  // 3: NodeToNode.SendPing:input_type -> Ping
	9,  // 4: NodeToNode.AskForVote:input_type -> VoteRequest
	11, // 5: NodeToNode.SendStateUpdate:input_type -> StateUpdate
	1,  // 6: NodeToNode.ForwardBid:input_type -> BidRequest
	2,  // 7: Bidding.Bid:output_type -> Acknowledgement
	4,  // 8: Auction.Subscribe:output_type -> Result
	6,  // 9: Query.GetAuctionStatus:output_type -> AuctionStatus
	8,  // 10: NodeToNode.SendPing:output_type -> PingReply
	10, // 11: NodeToNode.AskForVote:output_type -> VoteReply
	12, // 12: NodeToNode.SendStateUpdate:output_type -> StateAck
	2,  // 13: NodeToNode.ForwardBid:output_type -> Acknowledgement
	7,  // [7:14] is the sub-list for method output_type
	0,  // [0:7] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_grpc_proto_proto_init() }
func file_grpc_proto_proto_init() {
	if File_grpc_proto_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_grpc_proto_proto_rawDesc), len(file_grpc_proto_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   4,
		},
		GoTypes:           file_grpc_proto_proto_goTypes,
		DependencyIndexes: file_grpc_proto_proto_depIdxs,
		EnumInfos:         file_grpc_proto_proto_enumTypes,
		MessageInfos:      file_grpc_proto_proto_msgTypes,
	}.Build()
	File_grpc_proto_proto = out.File
	file_grpc_proto_proto_goTypes = nil
	file_grpc_proto_proto_depIdxs = nil
}
