// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.1
// source: grpc/proto.proto

package grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Bidding_Bid_FullMethodName = "/Bidding/Bid"
)

// BiddingClient is the client API for Bidding service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BiddingClient interface {
	Bid(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[BidRequest, Acknowledgement], error)
}

type biddingClient struct {
	cc grpc.ClientConnInterface
}

func NewBiddingClient(cc grpc.ClientConnInterface) BiddingClient {
	return &biddingClient{cc}
}

func (c *biddingClient) Bid(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[BidRequest, Acknowledgement], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Bidding_ServiceDesc.Streams[0], Bidding_Bid_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[BidRequest, Acknowledgement]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Bidding_BidClient = grpc.BidiStreamingClient[BidRequest, Acknowledgement]

// BiddingServer is the server API for Bidding service.
// All implementations must embed UnimplementedBiddingServer
// for forward compatibility.
type BiddingServer interface {
	Bid(grpc.BidiStreamingServer[BidRequest, Acknowledgement]) error
	mustEmbedUnimplementedBiddingServer()
}

// UnimplementedBiddingServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBiddingServer struct{}

func (UnimplementedBiddingServer) Bid(grpc.BidiStreamingServer[BidRequest, Acknowledgement]) error {
	return status.Errorf(codes.Unimplemented, "method Bid not implemented")
}
func (UnimplementedBiddingServer) mustEmbedUnimplementedBiddingServer() {}
func (UnimplementedBiddingServer) testEmbeddedByValue()                 {}

// UnsafeBiddingServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BiddingServer will
// result in compilation errors.
type UnsafeBiddingServer interface {
	mustEmbedUnimplementedBiddingServer()
}

func RegisterBiddingServer(s grpc.ServiceRegistrar, srv BiddingServer) {
	// If the following call pancis, it indicates UnimplementedBiddingServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Bidding_ServiceDesc, srv)
}

func _Bidding_Bid_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(BiddingServer).Bid(&grpc.GenericServerStream[BidRequest, Acknowledgement]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Bidding_BidServer = grpc.BidiStreamingServer[BidRequest, Acknowledgement]

// Bidding_ServiceDesc is the grpc.ServiceDesc for Bidding service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Bidding_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Bidding",
	HandlerType: (*BiddingServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Bid",
			Handler:       _Bidding_Bid_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "grpc/proto.proto",
}

const (
	Auction_Subscribe_FullMethodName = "/Auction/Subscribe"
)

// AuctionClient is the client API for Auction service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AuctionClient interface {
	Subscribe(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Result], error)
}

type auctionClient struct {
	cc grpc.ClientConnInterface
}

func NewAuctionClient(cc grpc.ClientConnInterface) AuctionClient {
	return &auctionClient{cc}
}

func (c *auctionClient) Subscribe(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Result], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Auction_ServiceDesc.Streams[0], Auction_Subscribe_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SubscribeRequest, Result]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Auction_SubscribeClient = grpc.ServerStreamingClient[Result]

// AuctionServer is the server API for Auction service.
// All implementations must embed UnimplementedAuctionServer
// for forward compatibility.
type AuctionServer interface {
	Subscribe(*SubscribeRequest, grpc.ServerStreamingServer[Result]) error
	mustEmbedUnimplementedAuctionServer()
}

// UnimplementedAuctionServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAuctionServer struct{}

func (UnimplementedAuctionServer) Subscribe(*SubscribeRequest, grpc.ServerStreamingServer[Result]) error {
	return status.Errorf(codes.Unimplemented, "method Subscribe not implemented")
}
func (UnimplementedAuctionServer) mustEmbedUnimplementedAuctionServer() {}
func (UnimplementedAuctionServer) testEmbeddedByValue()                 {}

// UnsafeAuctionServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AuctionServer will
// result in compilation errors.
type UnsafeAuctionServer interface {
	mustEmbedUnimplementedAuctionServer()
}

func RegisterAuctionServer(s grpc.ServiceRegistrar, srv AuctionServer) {
	// If the following call pancis, it indicates UnimplementedAuctionServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Auction_ServiceDesc, srv)
}

func _Auction_Subscribe_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AuctionServer).Subscribe(m, &grpc.GenericServerStream[SubscribeRequest, Result]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Auction_SubscribeServer = grpc.ServerStreamingServer[Result]

// Auction_ServiceDesc is the grpc.ServiceDesc for Auction service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Auction_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Auction",
	HandlerType: (*AuctionServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Subscribe",
			Handler:       _Auction_Subscribe_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "grpc/proto.proto",
}

const (
	Query_GetAuctionStatus_FullMethodName = "/Query/GetAuctionStatus"
)

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type QueryClient interface {
	GetAuctionStatus(ctx context.Context, in *QueryRequest, opts ...grpc.CallOption) (*AuctionStatus, error)
}

type queryClient struct {
	cc grpc.ClientConnInterface
}

func NewQueryClient(cc grpc.ClientConnInterface) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) GetAuctionStatus(ctx context.Context, in *QueryRequest, opts ...grpc.CallOption) (*AuctionStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AuctionStatus)
	err := c.cc.Invoke(ctx, Query_GetAuctionStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
// All implementations must embed UnimplementedQueryServer
// for forward compatibility.
type QueryServer interface {
	GetAuctionStatus(context.Context, *QueryRequest) (*AuctionStatus, error)
	mustEmbedUnimplementedQueryServer()
}

// UnimplementedQueryServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedQueryServer struct{}

func (UnimplementedQueryServer) GetAuctionStatus(context.Context, *QueryRequest) (*AuctionStatus, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAuctionStatus not implemented")
}
func (UnimplementedQueryServer) mustEmbedUnimplementedQueryServer() {}
func (UnimplementedQueryServer) testEmbeddedByValue()               {}

// UnsafeQueryServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to QueryServer will
// result in compilation errors.
type UnsafeQueryServer interface {
	mustEmbedUnimplementedQueryServer()
}

func RegisterQueryServer(s grpc.ServiceRegistrar, srv QueryServer) {
	// If the following call pancis, it indicates UnimplementedQueryServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Query_ServiceDesc, srv)
}

func _Query_GetAuctionStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).GetAuctionStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_GetAuctionStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).GetAuctionStatus(ctx, req.(*QueryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Query_ServiceDesc is the grpc.ServiceDesc for Query service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Query_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAuctionStatus",
			Handler:    _Query_GetAuctionStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "grpc/proto.proto",
}

const (
	NodeToNode_SendPing_FullMethodName        = "/NodeToNode/SendPing"
	NodeToNode_AskForVote_FullMethodName      = "/NodeToNode/AskForVote"
	NodeToNode_SendStateUpdate_FullMethodName = "/NodeToNode/SendStateUpdate"
)

// NodeToNodeClient is the client API for NodeToNode service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NodeToNodeClient interface {
	SendPing(ctx context.Context, in *Ping, opts ...grpc.CallOption) (*PingReply, error)
	AskForVote(ctx context.Context, in *VoteRequest, opts ...grpc.CallOption) (*VoteReply, error)
	SendStateUpdate(ctx context.Context, in *StateUpdate, opts ...grpc.CallOption) (*StateAck, error)
}

type nodeToNodeClient struct {
	cc grpc.ClientConnInterface
}

func NewNodeToNodeClient(cc grpc.ClientConnInterface) NodeToNodeClient {
	return &nodeToNodeClient{cc}
}

func (c *nodeToNodeClient) SendPing(ctx context.Context, in *Ping, opts ...grpc.CallOption) (*PingReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PingReply)
	err := c.cc.Invoke(ctx, NodeToNode_SendPing_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeToNodeClient) AskForVote(ctx context.Context, in *VoteRequest, opts ...grpc.CallOption) (*VoteReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VoteReply)
	err := c.cc.Invoke(ctx, NodeToNode_AskForVote_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeToNodeClient) SendStateUpdate(ctx context.Context, in *StateUpdate, opts ...grpc.CallOption) (*StateAck, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StateAck)
	err := c.cc.Invoke(ctx, NodeToNode_SendStateUpdate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NodeToNodeServer is the server API for NodeToNode service.
// All implementations must embed UnimplementedNodeToNodeServer
// for forward compatibility.
type NodeToNodeServer interface {
	SendPing(context.Context, *Ping) (*PingReply, error)
	AskForVote(context.Context, *VoteRequest) (*VoteReply, error)
	SendStateUpdate(context.Context, *StateUpdate) (*StateAck, error)
	mustEmbedUnimplementedNodeToNodeServer()
}

// UnimplementedNodeToNodeServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNodeToNodeServer struct{}

func (UnimplementedNodeToNodeServer) SendPing(context.Context, *Ping) (*PingReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendPing not implemented")
}
func (UnimplementedNodeToNodeServer) AskForVote(context.Context, *VoteRequest) (*VoteReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AskForVote not implemented")
}
func (UnimplementedNodeToNodeServer) SendStateUpdate(context.Context, *StateUpdate) (*StateAck, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendStateUpdate not implemented")
}
func (UnimplementedNodeToNodeServer) mustEmbedUnimplementedNodeToNodeServer() {}
func (UnimplementedNodeToNodeServer) testEmbeddedByValue()                    {}

// UnsafeNodeToNodeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NodeToNodeServer will
// result in compilation errors.
type UnsafeNodeToNodeServer interface {
	mustEmbedUnimplementedNodeToNodeServer()
}

func RegisterNodeToNodeServer(s grpc.ServiceRegistrar, srv NodeToNodeServer) {
	// If the following call pancis, it indicates UnimplementedNodeToNodeServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&NodeToNode_ServiceDesc, srv)
}

func _NodeToNode_SendPing_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Ping)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeToNodeServer).SendPing(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeToNode_SendPing_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeToNodeServer).SendPing(ctx, req.(*Ping))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeToNode_AskForVote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VoteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeToNodeServer).AskForVote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeToNode_AskForVote_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeToNodeServer).AskForVote(ctx, req.(*VoteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeToNode_SendStateUpdate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StateUpdate)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeToNodeServer).SendStateUpdate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeToNode_SendStateUpdate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeToNodeServer).SendStateUpdate(ctx, req.(*StateUpdate))
	}
	return interceptor(ctx, in, info, handler)
}

// NodeToNode_ServiceDesc is the grpc.ServiceDesc for NodeToNode service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NodeToNode_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "NodeToNode",
	HandlerType: (*NodeToNodeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendPing",
			Handler:    _NodeToNode_SendPing_Handler,
		},
		{
			MethodName: "AskForVote",
			Handler:    _NodeToNode_AskForVote_Handler,
		},
		{
			MethodName: "SendStateUpdate",
			Handler:    _NodeToNode_SendStateUpdate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "grpc/proto.proto",
}
